#!/usr/bin/env bash
# Pre-edit hook: block edits to generated or third-party files.
# Exit 2 blocks the edit; stderr is shown to the editor as the reason.
set -euo pipefail

FILE="$(jq -r '.tool_input.file_path // empty')"

case "$FILE" in
  */.terraform/* | */.terraform.lock.hcl)
    echo "Generated by terraform init. Change versions.tf and run terraform init -upgrade instead." >&2
    exit 2
    ;;
  */.secrets.baseline)
    echo "Regenerate with: detect-secrets scan --baseline .secrets.baseline" >&2
    exit 2
    ;;
  */docs/diagrams/*.svg | */docs/diagrams/*.png | */docs/assets/cover.png)
    echo "Exported diagram or cover. Edit the source in docs/diagrams/ and re-export." >&2
    exit 2
    ;;
esac
exit 0
